apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.dns }}
      dnsConfig:
        nameservers:
          {{- toYaml .nameservers | nindent 10 }}
      {{- end }}
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TELE_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: {{ .Values.telegramTokenKey }}
        ports:
        - name: http
          containerPort: {{ .Values.app.port }}
          protocol: TCP