---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentGatewayName }}
      namespace: {{ .Values.gateway.parentGatewayNamespace }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ template "helm.fullname" . }}
      port: {{ .Values.app.port }}
      weight: 1
    {{- with .Values.filters }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    matches:
    - path:
        type: PathPrefix
        value: {{ .Values.gateway.path }}
