apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: kbot
  namespace: demo
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxbot
        email: flux@local
      messageTemplate: |
        chore(kbot): automated image update to {{range .Updated.Images}}{{.NewTag}}{{end}}
    push:
      branch: main
  update:
    path: ./clusters/demo
    strategy: Setters
